"""
Pretrain ForgeNet on BFS expert demonstrations.

Reads expert_demos.pkl (list of (frame, action_idx, reward) tuples generated by
gen_pretrain_data.py), trains ForgeNet with the same BCE-on-logits loss the
agent uses, saves to pretrained_weights.pt for shipping as a Kaggle dataset.
"""

import pickle
import time
import sys
from collections import deque
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F


# ===================== ForgeNet (copied from v20_agent.py) =====================
class CBAM(nn.Module):
    def __init__(s, ch, r=16):
        super().__init__()
        s.fc1 = nn.Linear(ch, max(ch // r, 4))
        s.fc2 = nn.Linear(max(ch // r, 4), ch)
        s.sp = nn.Conv2d(2, 1, 7, padding=3)

    def forward(s, x):
        B, C, H, W = x.shape
        w = torch.sigmoid(s.fc2(F.relu(s.fc1(x.mean(dim=[2, 3])))))
        x = x * w.view(B, C, 1, 1)
        a = torch.sigmoid(s.sp(torch.cat([x.max(1, keepdim=True)[0], x.mean(1, keepdim=True)], 1)))
        return x * a


class ForgeNet(nn.Module):
    def __init__(s, in_ch=26, g=64):
        super().__init__()
        s.g = g
        s.c1 = nn.Conv2d(in_ch, 32, 3, padding=1); s.c2 = nn.Conv2d(32, 64, 3, padding=1)
        s.c3 = nn.Conv2d(64, 128, 3, padding=1);   s.c4 = nn.Conv2d(128, 256, 3, padding=1)
        s.attn = CBAM(256); s.ar = nn.Conv2d(256, 64, 1); s.ap = nn.MaxPool2d(4, 4)
        s.af = nn.Linear(64 * 16 * 16, 256); s.ah = nn.Linear(256, 5); s.dr = nn.Dropout(0.15)
        s.cc1 = nn.Conv2d(256, 128, 3, padding=1); s.cc2 = nn.Conv2d(128, 64, 3, padding=1)
        s.cc3 = nn.Conv2d(64, 32, 1); s.cc4 = nn.Conv2d(32, 1, 1)

    def forward(s, x):
        x = F.relu(s.c1(x)); x = F.relu(s.c2(x)); x = F.relu(s.c3(x)); f = F.relu(s.c4(x))
        f = s.attn(f); af = F.relu(s.ar(f)); af = s.ap(af).reshape(f.size(0), -1)
        al = s.ah(s.dr(F.relu(s.af(af))))
        cf = F.relu(s.cc1(f)); cf = F.relu(s.cc2(cf)); cf = F.relu(s.cc3(cf))
        cl = s.cc4(cf).reshape(f.size(0), -1)
        return torch.cat([al, cl], 1)


def encode_frame(frame: np.ndarray) -> torch.Tensor:
    """Convert a (64,64) int frame into 26-channel tensor.
    Note: Skips frame-history diff channels (last 5) — sets them to zero.
    The agent's runtime _tensor uses live history, but for pretraining we
    use a frame-only encoding and let the agent's training continue to
    fine-tune those channels online."""
    frame = frame.astype(np.int64)
    if frame.shape != (64, 64):
        return None
    oh = torch.zeros(16, 64, 64, dtype=torch.float32)
    oh.scatter_(0, torch.from_numpy(frame).unsqueeze(0), 1)
    cnt = np.bincount(frame.flatten(), minlength=16)
    bg = int(cnt.argmax()); mx = max(cnt.max(), 1)
    bg_m = (frame == bg).astype(np.float32)
    rar = np.zeros((64, 64), np.float32)
    for c in range(16):
        if cnt[c] > 0:
            rar[frame == c] = 1.0 - cnt[c] / mx
    pad = np.pad(frame, 1, mode='edge')
    edge = ((frame != pad[:-2, 1:-1]) | (frame != pad[2:, 1:-1])
            | (frame != pad[1:-1, :-2]) | (frame != pad[1:-1, 2:])).astype(np.float32)
    rp = np.linspace(0, 1, 64, dtype=np.float32).reshape(64, 1).repeat(64, 1)
    cp = np.linspace(0, 1, 64, dtype=np.float32).reshape(1, 64).repeat(64, 0)
    aug = torch.from_numpy(np.stack([bg_m, rar, edge, rp, cp]))
    d1 = torch.zeros(3, 64, 64, dtype=torch.float32)  # frame-diff channels: 0
    d2 = torch.zeros(2, 64, 64, dtype=torch.float32)
    return torch.cat([oh, aug, d1, d2], 0)


def main():
    pkl = Path("expert_demos.pkl")
    if not pkl.exists():
        print(f"Missing {pkl}; run gen_pretrain_data.py first")
        sys.exit(1)
    print(f"Loading {pkl} ({pkl.stat().st_size/1024:.1f} KB)")
    with open(pkl, "rb") as f:
        raw_samples = pickle.load(f)
    print(f"Loaded {len(raw_samples)} raw samples")
    samples = []
    for frame, aidx, reward in raw_samples:
        enc = encode_frame(frame)
        if enc is None:
            continue
        samples.append((enc, int(aidx), float(reward)))
    print(f"Encoded {len(samples)} samples")
    if len(samples) < 100:
        print("Too few; aborting")
        sys.exit(1)

    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f"Training on {device}")
    net = ForgeNet(in_ch=26, g=64).to(device)
    opt = torch.optim.Adam(net.parameters(), lr=1e-3)
    BSZ = 64
    EPOCHS = 20
    n = len(samples)
    t0 = time.time()
    for epoch in range(EPOCHS):
        np.random.shuffle(samples)
        losses = []
        for i in range(0, n - BSZ, BSZ):
            batch = samples[i:i + BSZ]
            states = torch.stack([b[0] for b in batch]).to(device)
            acts = torch.tensor([b[1] for b in batch], dtype=torch.long, device=device)
            rews = torch.tensor([b[2] for b in batch], dtype=torch.float32, device=device)
            rews = torch.sigmoid(rews)
            opt.zero_grad()
            logits = net(states)
            acts_c = acts.clamp(0, logits.size(1) - 1)
            sel = logits.gather(1, acts_c.unsqueeze(1)).squeeze(1)
            loss = F.binary_cross_entropy_with_logits(sel, rews)
            p = torch.sigmoid(logits)
            loss = loss - 0.0001 * p[:, :5].mean() - 0.00001 * p[:, 5:].mean()
            loss.backward()
            opt.step()
            losses.append(loss.item())
        print(f"epoch {epoch+1}/{EPOCHS}  loss={np.mean(losses):.4f}  elapsed={time.time()-t0:.0f}s")
    out = Path("pretrained_weights.pt")
    torch.save(net.state_dict(), out)
    print(f"Saved {out} ({out.stat().st_size/1024:.1f} KB)")


if __name__ == "__main__":
    main()
