"""Meta-harness prompt optimizer for AIMO3 — using kaos + Claude Code CLI.

Systematically optimizes text parameters (system_prompt, tool_prompt,
preference_prompt, voting strategy, time budgets) for our AIMO3 notebook
that runs GPT-OSS-120B with Harmony protocol on Kaggle.

Since we cannot run vLLM locally (10GB GPU), evaluation is done by having
Claude analyze which prompt configuration is likely better for IMO math,
using structured criteria. The best config is then applied to the Kaggle
notebook.

Usage:
    uv run python scripts/optimize_prompts.py --iterations 5
    uv run python scripts/optimize_prompts.py --iterations 10 --candidates 3
    uv run python scripts/optimize_prompts.py --export-best  # just dump current best

Requires:
    - claude CLI (Claude Code) available on PATH
    - kaos (from f:/kaggle/kaos/)
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import textwrap
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
sys.path.insert(0, "f:/kaggle/kaos")

from kaos import Kaos


# ── Configuration dataclass ────────────────────────────────────

@dataclass
class AIMO3Config:
    """All tunable text/strategy parameters for the AIMO3 notebook.

    Numeric params (temperature, attempts, etc.) are included so the
    proposer can reason about them holistically, but the main optimization
    targets are the text prompts and the voting logic.
    """

    # -- Text prompts (primary optimization targets) --
    system_prompt: str = ""
    tool_prompt: str = ""
    preference_prompt: str = ""

    # -- Voting strategy (Python code string) --
    voting_strategy: str = "inverse_entropy"
    voting_code: str = ""

    # -- Numeric parameters --
    attempts: int = 8
    early_stop: int = 4
    temperature: float = 1.0
    min_p: float = 0.02
    high_problem_timeout: int = 900
    base_problem_timeout: int = 270
    workers: int = 16
    turns: int = 128

    # -- Metadata --
    name: str = ""
    rationale: str = ""

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "AIMO3Config":
        valid_fields = {f.name for f in cls.__dataclass_fields__.values()}
        return cls(**{k: v for k, v in data.items() if k in valid_fields})

    def cfg_summary(self) -> str:
        """Compact summary for archive display."""
        lines = [
            f"Name: {self.name}",
            f"System prompt ({len(self.system_prompt)} chars): {self.system_prompt[:120]}...",
            f"Tool prompt ({len(self.tool_prompt)} chars): {self.tool_prompt[:80]}...",
            f"Preference prompt: {self.preference_prompt[:80]}...",
            f"Voting: {self.voting_strategy}",
            f"attempts={self.attempts}, early_stop={self.early_stop}, "
            f"temp={self.temperature}, min_p={self.min_p}",
            f"timeouts: high={self.high_problem_timeout}, base={self.base_problem_timeout}",
            f"workers={self.workers}, turns={self.turns}",
        ]
        return "\n".join(lines)

    def to_notebook_dict(self) -> str:
        """Export as a Python dict literal for pasting into the notebook."""
        return textwrap.dedent(f"""\
        # -- AIMO3 Optimized Config --
        # Generated by optimize_prompts.py
        # Candidate: {self.name}
        # Rationale: {self.rationale}

        class CFG:
            system_prompt = {self.system_prompt!r}

            tool_prompt = {self.tool_prompt!r}

            preference_prompt = {self.preference_prompt!r}

            served_model_name = 'gpt-oss'
            model_path = '/kaggle/input/models/danielhanchen/gpt-oss-120b/transformers/default/1'

            kv_cache_dtype = 'fp8_e4m3'
            dtype = 'auto'

            high_problem_timeout = {self.high_problem_timeout}
            base_problem_timeout = {self.base_problem_timeout}
            notebook_limit = 17400
            server_timeout = 180
            session_timeout = 960
            jupyter_timeout = 6
            sandbox_timeout = 3

            stream_interval = 200
            context_tokens = 81920
            batched_tokens = 2048
            buffer_tokens = 512
            search_tokens = 32
            capture_size = 64
            top_logprobs = 5
            batch_size = 64
            early_stop = {self.early_stop}
            attempts = {self.attempts}
            workers = {self.workers}
            turns = {self.turns}
            seed = 42

            gpu_memory_utilization = 0.99
            temperature = {self.temperature}
            min_p = {self.min_p}

        # Voting strategy: {self.voting_strategy}
        # {self.voting_code.replace(chr(10), chr(10) + '# ') if self.voting_code else 'default inverse entropy'}
        """)


# ── Seed configurations ────────────────────────────────────────

SEED_BASELINE = AIMO3Config(
    name="baseline_v18",
    rationale="Exact config from v18 notebook (mirrors top 43/50 public notebook)",
    system_prompt=(
        "You are a world-class International Mathematical Olympiad (IMO) competitor. "
        "The final answer must be a non-negative integer between 0 and 99999. "
        "You must place the final integer answer inside \\boxed{}."
    ),
    tool_prompt=(
        "Use this tool to execute Python code. "
        "The environment is a stateful Jupyter notebook. "
        "You must use print() to output results."
    ),
    preference_prompt=(
        "You have access to `math`, `numpy` and `sympy` to solve the problem."
    ),
    voting_strategy="inverse_entropy",
    voting_code="weight = 1.0 / max(entropy, 1e-9)",
    attempts=8,
    early_stop=4,
    temperature=1.0,
    min_p=0.02,
    high_problem_timeout=900,
    base_problem_timeout=270,
    workers=16,
    turns=128,
)

SEED_ENHANCED_PROMPT = AIMO3Config(
    name="enhanced_system_prompt",
    rationale=(
        "More detailed system prompt with explicit chain-of-thought instructions, "
        "verification emphasis, and modular arithmetic reminder. Hypothesis: "
        "stronger prompt guidance improves accuracy on number theory and algebra."
    ),
    system_prompt=(
        "You are a world-class International Mathematical Olympiad (IMO) competitor "
        "with expertise in algebra, combinatorics, geometry, and number theory. "
        "Approach each problem methodically:\n"
        "1. Identify the problem type and relevant techniques.\n"
        "2. Write Python code to explore small cases and form conjectures.\n"
        "3. Prove or verify your conjecture computationally.\n"
        "4. Double-check edge cases and boundary conditions.\n"
        "5. Compute the final integer answer (0-99999).\n"
        "The final answer must be a non-negative integer between 0 and 99999. "
        "You must place the final integer answer inside \\boxed{}.\n"
        "IMPORTANT: If the answer involves modular arithmetic, compute the exact remainder. "
        "Always verify your answer with a separate computation before boxing it."
    ),
    tool_prompt=(
        "Use this tool to execute Python code in a stateful Jupyter notebook. "
        "You must use print() to see results. Available libraries: math, numpy, sympy, "
        "mpmath (with 64 decimal digits precision), itertools, collections. "
        "Previous variables persist between calls."
    ),
    preference_prompt=(
        "You have access to `math`, `numpy`, `sympy`, `mpmath` (64 decimal digits), "
        "`itertools`, and `collections` to solve the problem. "
        "Use code to verify every step."
    ),
    voting_strategy="inverse_entropy",
    voting_code="weight = 1.0 / max(entropy, 1e-9)",
    attempts=8,
    early_stop=4,
    temperature=1.0,
    min_p=0.02,
    high_problem_timeout=900,
    base_problem_timeout=270,
    workers=16,
    turns=128,
)

SEED_NIHILIST_VOTING = AIMO3Config(
    name="nihilist_5comp_voting",
    rationale=(
        "Adapted from nihilisticneuralnet (43/50 public LB). Uses a 5-component "
        "entropy scoring formula: position-weighted entropy, variance penalty, "
        "sustained high-entropy penalty, and streak bonus. Hypothesis: "
        "more nuanced confidence weighting picks better answers when attempts disagree."
    ),
    system_prompt=(
        "You are a world-class International Mathematical Olympiad (IMO) competitor. "
        "The final answer must be a non-negative integer between 0 and 99999. "
        "You must place the final integer answer inside \\boxed{}."
    ),
    tool_prompt=(
        "Use this tool to execute Python code. "
        "The environment is a stateful Jupyter notebook. "
        "You must use print() to output results."
    ),
    preference_prompt=(
        "You have access to `math`, `numpy` and `sympy` to solve the problem."
    ),
    voting_strategy="nihilist_5component",
    voting_code=textwrap.dedent("""\
        import numpy as np
        weights_pos = np.array([0.995 ** (n - i - 1) for i in range(n)])
        position_weighted_ent = np.sum(weights_pos * entropies_arr) / np.sum(weights_pos)
        std_dev = np.std(entropies_arr)
        high_ent_ratio = np.sum(entropies_arr > 1.5) / n
        # Streak bonus for consecutive low-entropy tokens
        max_streak = 0; cur = 0
        for e in entropies_arr:
            if e < 0.5: cur += 1; max_streak = max(max_streak, cur)
            else: cur = 0
        streak_bonus = -0.05 * max_streak if max_streak > 10 else 0
        final_entropy = (
            0.3 * mean_ent + 0.4 * position_weighted_ent +
            0.2 * std_dev + 0.3 * high_ent_ratio * 3.0 + streak_bonus
        )
        weight = 1.0 / max(final_entropy, 1e-9)
    """),
    attempts=8,
    early_stop=4,
    temperature=1.0,
    min_p=0.02,
    high_problem_timeout=900,
    base_problem_timeout=270,
    workers=16,
    turns=128,
)

SEED_AGGRESSIVE_TIME = AIMO3Config(
    name="aggressive_time_budget",
    rationale=(
        "More aggressive time management: higher timeout for hard problems (1200s), "
        "lower base for easy ones (210s), more attempts (10) but higher early_stop (5). "
        "Hypothesis: harder problems benefit from more compute; easy ones are solved "
        "in fewer attempts, freeing time budget."
    ),
    system_prompt=(
        "You are a world-class International Mathematical Olympiad (IMO) competitor. "
        "The final answer must be a non-negative integer between 0 and 99999. "
        "You must place the final integer answer inside \\boxed{}."
    ),
    tool_prompt=(
        "Use this tool to execute Python code. "
        "The environment is a stateful Jupyter notebook. "
        "You must use print() to output results."
    ),
    preference_prompt=(
        "You have access to `math`, `numpy` and `sympy` to solve the problem."
    ),
    voting_strategy="inverse_entropy",
    voting_code="weight = 1.0 / max(entropy, 1e-9)",
    attempts=10,
    early_stop=5,
    temperature=1.0,
    min_p=0.02,
    high_problem_timeout=1200,
    base_problem_timeout=210,
    workers=16,
    turns=128,
)

ALL_SEEDS = [SEED_BASELINE, SEED_ENHANCED_PROMPT, SEED_NIHILIST_VOTING, SEED_AGGRESSIVE_TIME]


# ── Evaluation criteria ────────────────────────────────────────

EVALUATION_CRITERIA = textwrap.dedent("""\
    ## IMO Math Prompt Evaluation Criteria

    Score each configuration on these axes (1-10 scale):

    1. **Clarity of instructions** (1-10): Does the system prompt clearly tell
       the model what to do? Does it avoid ambiguity? IMO problems need precise
       instructions about output format (\\boxed{} with integer), modular
       arithmetic, and the expected range (0-99999).

    2. **Encouragement of code use** (1-10): The model MUST use Python/sympy to
       solve problems. Prompts that explicitly encourage code-first thinking and
       verification score higher. The tool prompt should mention statefulness,
       print() requirement, and available libraries.

    3. **Verification emphasis** (1-10): Does the prompt encourage the model to
       double-check its answer? On IMO problems, verification catches 10-20% of
       errors. Prompts that tell the model to "verify with a separate computation"
       or "check edge cases" score higher.

    4. **Domain coverage** (1-10): IMO covers algebra, combinatorics, geometry,
       and number theory. Does the prompt help the model recognize which domain
       applies? Generic prompts score lower than those with domain-aware guidance.

    5. **Voting strategy quality** (1-10): For 8 parallel attempts with early_stop,
       how well does the voting strategy select the correct answer? Simple majority
       is weak. Inverse entropy is good. Multi-component entropy is better.
       Strategies that incorporate code execution success are best.

    6. **Time budget efficiency** (1-10): With 50 problems in ~17400 seconds, the
       budget must balance hard vs easy problems. Generous high_timeout with modest
       base_timeout plus early_stop is the proven pattern. Very aggressive budgets
       risk running out of time.

    7. **Risk of regression** (1-10, inverted: 10=lowest risk): Changes that
       differ minimally from the proven top-notebook config carry lower risk.
       Novel prompt styles or untested voting formulas carry higher risk.

    8. **Novel insight** (1-10): Does this config introduce a genuinely new idea
       that could improve accuracy? Pure copies of existing configs score low.
       Targeted additions (e.g., explicit modular arithmetic reminder) score higher.

    Compute an overall score as:
        overall = (0.20 * clarity + 0.20 * code_use + 0.15 * verification
                 + 0.10 * domain + 0.15 * voting + 0.10 * time_budget
                 + 0.05 * risk_inv + 0.05 * novelty)
""")

# ── Reference problems for reasoning ──────────────────────────

REFERENCE_PROBLEMS = [
    {
        "id": "imo2024_p1",
        "text": (
            "Determine all real numbers α such that, for every positive integer n, "
            "the integer ⌊α⌋ + ⌊2α⌋ + ... + ⌊nα⌋ is a multiple of n."
        ),
        "domain": "number_theory",
        "difficulty": "medium",
        "answer_type": "characterization",
    },
    {
        "id": "imo2024_p5",
        "text": (
            "Turbo the snail plays a game on a board with 2024 rows and 2023 columns. "
            "There are hidden monsters in 2022 of the cells. "
            "Turbo makes at most one arrow per column. Determine the maximum value of n."
        ),
        "domain": "combinatorics",
        "difficulty": "hard",
        "answer_type": "integer",
    },
    {
        "id": "aime2025_p12",
        "text": (
            "Let p be a prime and let S be the set of integers x with 1 <= x <= p-1 "
            "such that x and p-x are both quadratic residues modulo p. "
            "Find the remainder when the product of elements of S is divided by p."
        ),
        "domain": "number_theory",
        "difficulty": "hard",
        "answer_type": "integer_mod",
    },
    {
        "id": "aime2025_p8",
        "text": (
            "A regular octahedron has vertices at distance 1 from the origin. "
            "A random plane through the origin intersects the octahedron. "
            "Find the expected area of the cross-section."
        ),
        "domain": "geometry",
        "difficulty": "medium",
        "answer_type": "integer",
    },
    {
        "id": "putnam2024_b3",
        "text": (
            "Find all continuous functions f: R -> R such that "
            "f(x) + f(y) = f(x+y) + f(xy) for all x, y in R."
        ),
        "domain": "algebra",
        "difficulty": "hard",
        "answer_type": "characterization",
    },
]


# ── Claude Code CLI proposer ──────────────────────────────────

def call_claude(prompt: str, system: str = "", timeout: int = 300) -> str:
    """Call Claude Code CLI with --print flag. No API keys needed."""
    import shutil
    claude_bin = (
        os.environ.get("CLAUDE_BIN")
        or shutil.which("claude")
        or shutil.which("claude.cmd")
        or r"C:\Users\dcani\AppData\Roaming\npm\claude.cmd"
    )
    # Remove CLAUDECODE env var to allow nested sessions
    env = os.environ.copy()
    env.pop("CLAUDECODE", None)
    env.pop("CLAUDE_CODE", None)
    # Pipe prompt via stdin — must use bytes to avoid Windows encoding issues
    cmd = [claude_bin, "--print", "--output-format", "text"]
    if system:
        cmd.extend(["--system-prompt", system[:2000]])
    try:
        result = subprocess.run(
            cmd,
            input=prompt.encode("utf-8"),
            capture_output=True,
            timeout=timeout,
            env=env,
        )
        # Decode output
        result = subprocess.CompletedProcess(
            result.args, result.returncode,
            stdout=result.stdout.decode("utf-8", errors="replace"),
            stderr=result.stderr.decode("utf-8", errors="replace"),
        )
        if result.returncode != 0:
            print(f"  [WARN] Claude CLI exit code {result.returncode}")
            if result.stderr:
                print(f"  stderr: {result.stderr[:300]}")
        return result.stdout.strip()
    except subprocess.TimeoutExpired:
        print(f"  [WARN] Claude CLI timed out after {timeout}s")
        return ""
    except FileNotFoundError:
        print("  [ERROR] 'claude' CLI not found on PATH. Install Claude Code first.")
        sys.exit(1)


def evaluate_config(config: AIMO3Config, all_configs: list[dict]) -> dict:
    """Use Claude to evaluate a config against the criteria.

    Returns a dict with per-criterion scores and an overall score.
    """
    # Build a concise summary of all prior configs for context
    prior_summaries = []
    for c in all_configs:
        scores = c.get("scores", {})
        overall = scores.get("overall", 0)
        prior_summaries.append(
            f"- {c['config']['name']} (overall={overall:.2f}): "
            f"{c['config'].get('rationale', 'no rationale')[:120]}"
        )
    prior_text = "\n".join(prior_summaries) if prior_summaries else "(no prior evaluations)"

    # Build the reference problems section
    problems_text = "\n".join(
        f"- [{p['id']}] ({p['domain']}, {p['difficulty']}): {p['text'][:150]}..."
        for p in REFERENCE_PROBLEMS
    )

    system = textwrap.dedent("""\
        You are an expert evaluator of LLM configurations for mathematical
        olympiad problem solving. You evaluate system prompts, tool prompts,
        voting strategies, and time budgets for a notebook that uses GPT-OSS-120B
        with Harmony protocol to solve IMO-level problems.

        Your evaluation must be rigorous, quantitative, and grounded in what
        is known to work from competition leaderboards.

        IMPORTANT: Output ONLY valid JSON. No markdown, no commentary.
    """)

    prompt = textwrap.dedent(f"""\
        Evaluate this AIMO3 configuration:

        {config.cfg_summary()}

        Voting code:
        ```
        {config.voting_code}
        ```

        Full system prompt:
        ```
        {config.system_prompt}
        ```

        Full tool prompt:
        ```
        {config.tool_prompt}
        ```

        Full preference prompt:
        ```
        {config.preference_prompt}
        ```

        {EVALUATION_CRITERIA}

        ## Reference problems this config would be tested on:
        {problems_text}

        ## Prior evaluated configs (for relative comparison):
        {prior_text}

        Think about how this config would perform on each reference problem.
        Consider: Would the system prompt help the model identify the problem type?
        Would the tool prompt encourage code-first verification? Would the voting
        strategy select the correct answer when attempts disagree?

        Output a JSON object with this exact structure:
        {{
            "clarity": <1-10>,
            "code_use": <1-10>,
            "verification": <1-10>,
            "domain": <1-10>,
            "voting": <1-10>,
            "time_budget": <1-10>,
            "risk_inv": <1-10>,
            "novelty": <1-10>,
            "overall": <weighted average as float>,
            "strengths": ["...", "..."],
            "weaknesses": ["...", "..."],
            "suggestion": "one-line suggestion for improvement"
        }}
    """)

    response = call_claude(prompt, system=system)
    if not response:
        return _default_scores()

    # Parse JSON from response
    return _extract_json(response)


def propose_new_config(
    archive: list[dict],
    iteration: int,
    n_candidates: int,
) -> list[AIMO3Config]:
    """Use Claude to propose new configs based on the archive."""

    # Build archive summary
    archive_lines = []
    for entry in sorted(archive, key=lambda x: x.get("scores", {}).get("overall", 0), reverse=True):
        cfg = entry["config"]
        scores = entry.get("scores", {})
        overall = scores.get("overall", 0)
        strengths = scores.get("strengths", [])
        weaknesses = scores.get("weaknesses", [])
        suggestion = scores.get("suggestion", "")
        archive_lines.append(textwrap.dedent(f"""\
            ### {cfg['name']} (overall={overall:.2f}, iter={entry.get('iteration', 0)})
            Rationale: {cfg.get('rationale', 'N/A')}
            System prompt: {cfg['system_prompt'][:200]}...
            Tool prompt: {cfg['tool_prompt'][:150]}...
            Preference: {cfg['preference_prompt'][:100]}...
            Voting: {cfg.get('voting_strategy', 'inverse_entropy')}
            Params: attempts={cfg.get('attempts', 8)}, early_stop={cfg.get('early_stop', 4)}, temp={cfg.get('temperature', 1.0)}, min_p={cfg.get('min_p', 0.02)}
            Timeouts: high={cfg.get('high_problem_timeout', 900)}, base={cfg.get('base_problem_timeout', 270)}
            Strengths: {', '.join(strengths[:3]) if strengths else 'N/A'}
            Weaknesses: {', '.join(weaknesses[:3]) if weaknesses else 'N/A'}
            Evaluator suggestion: {suggestion}
        """))
    archive_text = "\n".join(archive_lines) if archive_lines else "(no prior candidates)"

    problems_text = "\n".join(
        f"- [{p['id']}] ({p['domain']}, {p['difficulty']}): {p['text'][:150]}..."
        for p in REFERENCE_PROBLEMS
    )

    system = textwrap.dedent("""\
        You are a Meta-Harness proposer for AIMO3 — an IMO-level math competition
        where GPT-OSS-120B solves 50 problems using Harmony protocol with TIR (Tool
        Integrated Reasoning). The model runs on Kaggle with 2xH100 GPUs, vLLM server,
        and 16 parallel Jupyter kernels.

        Your job: analyze prior configurations and their evaluation scores, then
        propose NEW configurations that should score higher. Focus on:

        1. System prompt wording — what instructions make the model solve harder?
        2. Tool prompt details — what library/statefulness hints help?
        3. Preference prompt — what tools/approaches should be mentioned?
        4. Voting strategy — how to pick the best answer from N attempts?
        5. Time budgets — how to allocate 17400 seconds across 50 problems?

        Key constraints:
        - The model is GPT-OSS-120B via Harmony protocol (NOT chat completions)
        - ReasoningEffort.HIGH is always set (in the Harmony SystemContent)
        - The model uses stop_token_ids for tool calls (not text markers)
        - Temperature MUST stay at 1.0 (the model was trained for it)
        - min_p MUST stay at 0.02 (proven optimal)
        - context_tokens = 81920 (fixed by vLLM config)
        - The model can execute Python in a stateful Jupyter kernel

        IMPORTANT: Output ONLY valid JSON array. No markdown, no commentary.
    """)

    prompt = textwrap.dedent(f"""\
        This is iteration {iteration} of the meta-harness prompt optimization.

        ## Archive of all evaluated configs (sorted by score):
        {archive_text}

        ## Reference problems the configs will face:
        {problems_text}

        ## Your task:
        Propose exactly {n_candidates} new configuration(s). Each must explore a
        DIFFERENT improvement hypothesis. For each, provide the COMPLETE config
        (all fields filled in, not just diffs).

        Focus on what the evaluator's "suggestion" fields say, and address the
        "weaknesses" identified in top-scoring configs.

        Avoid repeating configs that already exist in the archive. Each new config
        should have a clear, testable hypothesis in its rationale.

        Output a JSON array of {n_candidates} objects, each with these keys:
        {{
            "name": "short_descriptive_name",
            "rationale": "1-2 sentence hypothesis",
            "system_prompt": "full system prompt text",
            "tool_prompt": "full tool prompt text",
            "preference_prompt": "full preference prompt text",
            "voting_strategy": "name_of_strategy",
            "voting_code": "Python code for the voting weight computation",
            "attempts": <int>,
            "early_stop": <int>,
            "temperature": 1.0,
            "min_p": 0.02,
            "high_problem_timeout": <int>,
            "base_problem_timeout": <int>,
            "workers": 16,
            "turns": <int>
        }}
    """)

    response = call_claude(prompt, system=system, timeout=600)
    if not response:
        return []

    # Parse JSON array
    candidates = _extract_json_array(response)
    configs = []
    for c in candidates[:n_candidates]:
        try:
            cfg = AIMO3Config.from_dict(c)
            configs.append(cfg)
        except Exception as e:
            print(f"  [WARN] Could not parse candidate: {e}")
    return configs


# ── JSON extraction helpers ────────────────────────────────────

def _extract_json(text: str) -> dict:
    """Extract a JSON object from a response that may contain other text."""
    # Try direct parse first
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Find JSON object in text
    start = text.find("{")
    if start == -1:
        return _default_scores()

    depth = 0
    for i in range(start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                try:
                    result = json.loads(text[start : i + 1])
                    # Ensure overall is computed if missing
                    if "overall" not in result:
                        result["overall"] = _compute_overall(result)
                    return result
                except json.JSONDecodeError:
                    pass
                break

    return _default_scores()


def _extract_json_array(text: str) -> list[dict]:
    """Extract a JSON array from a response."""
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    start = text.find("[")
    if start == -1:
        return []

    depth = 0
    for i in range(start, len(text)):
        if text[i] == "[":
            depth += 1
        elif text[i] == "]":
            depth -= 1
            if depth == 0:
                try:
                    return json.loads(text[start : i + 1])
                except json.JSONDecodeError:
                    pass
                break

    return []


def _default_scores() -> dict:
    return {
        "clarity": 5, "code_use": 5, "verification": 5, "domain": 5,
        "voting": 5, "time_budget": 5, "risk_inv": 5, "novelty": 5,
        "overall": 5.0, "strengths": [], "weaknesses": [],
        "suggestion": "evaluation failed",
    }


def _compute_overall(scores: dict) -> float:
    weights = {
        "clarity": 0.20, "code_use": 0.20, "verification": 0.15,
        "domain": 0.10, "voting": 0.15, "time_budget": 0.10,
        "risk_inv": 0.05, "novelty": 0.05,
    }
    total = 0.0
    for key, w in weights.items():
        total += w * float(scores.get(key, 5))
    return round(total, 4)


# ── Main search loop ──────────────────────────────────────────

def run_search(
    iterations: int,
    candidates_per_iter: int,
    db_path: str,
):
    """Execute the meta-harness prompt optimization loop."""
    db = Kaos(db_path)
    search_id = db.spawn("aimo3-prompt-optimizer", config={
        "type": "prompt_optimization",
        "iterations": iterations,
        "candidates_per_iter": candidates_per_iter,
    })
    db.set_status(search_id, "running")

    archive: list[dict] = []

    print("=" * 70)
    print("META-HARNESS PROMPT OPTIMIZER — AIMO3")
    print("=" * 70)
    print(f"  Iterations: {iterations}")
    print(f"  Candidates per iteration: {candidates_per_iter}")
    print(f"  Seeds: {len(ALL_SEEDS)}")
    print(f"  Database: {db_path}")
    print()

    # ── Step 1: Evaluate seeds ──
    print("--- Evaluating seed configurations ---\n")
    for seed_cfg in ALL_SEEDS:
        print(f"  Evaluating: {seed_cfg.name}")
        t0 = time.time()
        scores = evaluate_config(seed_cfg, archive)
        elapsed = time.time() - t0
        print(f"    overall={scores.get('overall', 0):.2f} ({elapsed:.1f}s)")
        for dim in ["clarity", "code_use", "verification", "domain", "voting", "time_budget"]:
            print(f"      {dim}: {scores.get(dim, '?')}")
        if scores.get("strengths"):
            print(f"    + {scores['strengths'][0]}")
        if scores.get("weaknesses"):
            print(f"    - {scores['weaknesses'][0]}")

        entry = {
            "config": seed_cfg.to_dict(),
            "scores": scores,
            "iteration": 0,
        }
        archive.append(entry)

        # Store in kaos
        name = seed_cfg.name
        db.write(search_id, f"/configs/{name}/config.json",
                 json.dumps(seed_cfg.to_dict(), indent=2).encode())
        db.write(search_id, f"/configs/{name}/scores.json",
                 json.dumps(scores, indent=2).encode())
        print()

    db.checkpoint(search_id, label="seeds-evaluated")

    # ── Step 2: Main optimization loop ──
    for iteration in range(1, iterations + 1):
        print(f"\n{'=' * 70}")
        print(f"ITERATION {iteration}/{iterations}")
        print(f"{'=' * 70}\n")

        # Propose new configs
        print("  Proposing via Claude Code CLI...")
        t0 = time.time()
        new_configs = propose_new_config(archive, iteration, candidates_per_iter)
        propose_time = time.time() - t0
        print(f"  Proposed {len(new_configs)} candidates in {propose_time:.1f}s\n")

        if not new_configs:
            print("  [WARN] No candidates proposed, skipping iteration")
            continue

        # Evaluate each new config
        for cfg in new_configs:
            print(f"  Evaluating: {cfg.name}")
            t0 = time.time()
            scores = evaluate_config(cfg, archive)
            elapsed = time.time() - t0
            print(f"    overall={scores.get('overall', 0):.2f} ({elapsed:.1f}s)")
            for dim in ["clarity", "code_use", "verification", "voting"]:
                print(f"      {dim}: {scores.get(dim, '?')}")
            if scores.get("suggestion"):
                print(f"    suggestion: {scores['suggestion']}")

            entry = {
                "config": cfg.to_dict(),
                "scores": scores,
                "iteration": iteration,
            }
            archive.append(entry)

            # Store in kaos
            name = f"iter{iteration}_{cfg.name}"
            db.write(search_id, f"/configs/{name}/config.json",
                     json.dumps(cfg.to_dict(), indent=2).encode())
            db.write(search_id, f"/configs/{name}/scores.json",
                     json.dumps(scores, indent=2).encode())
            print()

        # Checkpoint
        db.checkpoint(search_id, label=f"iter-{iteration}")

        # Show current leaderboard
        ranked = sorted(archive, key=lambda x: x["scores"].get("overall", 0), reverse=True)
        print("  Current leaderboard:")
        for i, entry in enumerate(ranked[:5]):
            cfg_name = entry["config"]["name"]
            overall = entry["scores"].get("overall", 0)
            it = entry.get("iteration", 0)
            print(f"    #{i+1}: {cfg_name:35s} overall={overall:.2f} (iter {it})")

        # Store leaderboard
        db.set_state(search_id, "current_iteration", iteration)
        db.set_state(search_id, "leaderboard", [
            {"name": e["config"]["name"], "overall": e["scores"].get("overall", 0),
             "iteration": e.get("iteration", 0)}
            for e in ranked
        ])

    # ── Step 3: Final results ──
    print("\n" + "=" * 70)
    print("FINAL RESULTS")
    print("=" * 70)

    ranked = sorted(archive, key=lambda x: x["scores"].get("overall", 0), reverse=True)
    for i, entry in enumerate(ranked):
        cfg = entry["config"]
        scores = entry["scores"]
        overall = scores.get("overall", 0)
        it = entry.get("iteration", 0)
        print(
            f"  #{i+1}: {cfg['name']:35s} overall={overall:.2f} (iter {it}) "
            f"| clar={scores.get('clarity', '?')} code={scores.get('code_use', '?')} "
            f"verif={scores.get('verification', '?')} vote={scores.get('voting', '?')}"
        )

    # Export best config
    best = ranked[0]
    best_cfg = AIMO3Config.from_dict(best["config"])
    export_path = Path(__file__).parent.parent / "data" / "best_config.py"
    export_path.parent.mkdir(parents=True, exist_ok=True)
    export_path.write_text(best_cfg.to_notebook_dict())
    print(f"\nBest config exported to: {export_path}")
    print(f"  Name: {best_cfg.name}")
    print(f"  Overall score: {best['scores'].get('overall', 0):.2f}")
    print(f"  Rationale: {best_cfg.rationale}")

    # Also export as JSON for machine consumption
    json_path = Path(__file__).parent.parent / "data" / "best_config.json"
    json_path.write_text(json.dumps({
        "config": best["config"],
        "scores": best["scores"],
    }, indent=2))
    print(f"  JSON: {json_path}")

    # Store final archive
    db.write(search_id, "/final_archive.json",
             json.dumps(archive, indent=2).encode())
    db.write(search_id, "/best_config.py",
             best_cfg.to_notebook_dict().encode())
    db.complete(search_id)
    db.close()

    print(f"\nAll data saved in {db_path}")
    return best_cfg


def export_best(db_path: str):
    """Export the current best config from an existing database."""
    db = Kaos(db_path)

    # Find the search agent
    agents = db.list_agents()
    search_agents = [a for a in agents if "prompt-optimizer" in a["name"]]
    if not search_agents:
        print("No prompt optimization runs found in database.")
        db.close()
        return

    search_id = search_agents[-1]["agent_id"]
    print(f"Search agent: {search_id[:14]}...")

    # Read the archive
    try:
        archive_data = db.read(search_id, "/final_archive.json")
        archive = json.loads(archive_data.decode())
    except FileNotFoundError:
        print("No final archive found. Run the search first.")
        db.close()
        return

    ranked = sorted(archive, key=lambda x: x["scores"].get("overall", 0), reverse=True)

    print("\nAll configs ranked by score:")
    for i, entry in enumerate(ranked):
        cfg = entry["config"]
        overall = entry["scores"].get("overall", 0)
        it = entry.get("iteration", 0)
        print(f"  #{i+1}: {cfg['name']:35s} overall={overall:.2f} (iter {it})")

    best = ranked[0]
    best_cfg = AIMO3Config.from_dict(best["config"])

    export_path = Path(__file__).parent.parent / "data" / "best_config.py"
    export_path.parent.mkdir(parents=True, exist_ok=True)
    export_path.write_text(best_cfg.to_notebook_dict())
    print(f"\nExported to: {export_path}")
    print(f"\nBest config notebook code:\n")
    print(best_cfg.to_notebook_dict())

    db.close()


# ── CLI ────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Meta-harness prompt optimizer for AIMO3",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              # Quick 3-iteration run:
              uv run python scripts/optimize_prompts.py --iterations 3

              # Full 10-iteration search with 3 candidates per iteration:
              uv run python scripts/optimize_prompts.py --iterations 10 --candidates 3

              # Export the current best from a previous run:
              uv run python scripts/optimize_prompts.py --export-best

              # Use a custom database path:
              uv run python scripts/optimize_prompts.py --iterations 5 --db my_search.db
        """),
    )
    parser.add_argument(
        "--iterations", type=int, default=5,
        help="Number of propose-evaluate iterations (default: 5)",
    )
    parser.add_argument(
        "--candidates", type=int, default=2,
        help="Candidates to propose per iteration (default: 2)",
    )
    parser.add_argument(
        "--db", default="aimo3-prompt-search.db",
        help="SQLite database path (default: aimo3-prompt-search.db)",
    )
    parser.add_argument(
        "--export-best", action="store_true",
        help="Just export the best config from an existing database",
    )
    args = parser.parse_args()

    if args.export_best:
        export_best(args.db)
    else:
        run_search(
            iterations=args.iterations,
            candidates_per_iter=args.candidates,
            db_path=args.db,
        )


if __name__ == "__main__":
    main()
